version: '3'

tasks:
  build:
    cmds:
      - go build -o ./startctl.exe
    desc: "Build the startctl application."

  run:
    cmds:
      - go run main.go
    desc: "Run the startctl application in development mode."
    sources:
      - "**/*.go"
    generates:
      - startctl 
  
  gosec:
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - gosec ./...
    desc: "Run gosec to check for security vulnerabilities."

  osv-scanner:
    cmds:
      - go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest
      - osv-scanner scan .
    desc: "Run osv-scanner to check for vulnerabilities."

  fmt:
    cmds:
      - go fmt ./...
    desc: "Run go fmt to format the entire project."
