name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Cross-compile for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o startctl.exe

    - name: Release Please
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: go
        package-name: startctl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: |
        git push --follow-tags origin main

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: startctl.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 