name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run gosec for security vulnerabilities
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: Run osv-scanner for vulnerabilities
      run: |
        go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest
        osv-scanner scan .

    - name: Cross-compile for Windows
      run: |
        go build -ldflags="-s -w" -o startctl.exe

    - name: Generate SHA256 checksum
      run: |
        CertUtil -hashfile startctl.exe SHA256 > startctl.exe.sha256

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      id: bump_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        name: Release v${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          startctl.exe
          startctl.exe.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}